name: Build and Publish on Release Tag

on:
  push:
    tags:
    - '*.*.*'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GCP_REGION: europe-west4
  GKE_CLUSTER: gke-0
  IMAGE: flowdber
  GCR: eu.gcr.io

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        VERSION=${{github.ref_name}}
        docker build \
          -t $GCR/"$GKE_PROJECT"/"$IMAGE":latest \
          -t $GCR/"$GKE_PROJECT"/"$IMAGE":${VERSION} \
          -t flowlab/"$IMAGE":latest \
          -t flowlab/"$IMAGE":"${VERSION}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg VERSION=${VERSION} .

    - name: Setup DockerHub
      run: |
        docker login --username flowlab --password ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish DockerHub
      run: |
        docker push flowlab/$IMAGE