name: Build and Publish

on:
  push:
    tags:
    - '*'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GCP_REGION: europe-west4
  GKE_CLUSTER: gke-0
  IMAGE: flowdber
  GCR: eu.gcr.io

jobs:
  setup-build-publish:
    name: Setup, Build and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup project version
    - name: Get version
      id: version
      run: |
        VERSION="dev"
        if [[ "${GITHUB_REF/refs\/tags\//}" != "refs/heads/"* ]] ; then
          VERSION="${GITHUB_REF/refs\/tags\//}"
        fi
        echo ::set-output name=VERSION::${VERSION}

    # Setup gcloud CLI
    # FIXME [grokrz]: this is not working
#    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#      with:
#        version: '270.0.0'
#        service_account_email: ${{ secrets.GKE_EMAIL }}
#        service_account_key: ${{ secrets.GKE_KEY }}

#    # Configure docker to use the gcloud command-line tool as a credential helper
#    - run: |
#        # Set up docker to authenticate
#        # via gcloud command-line tool.
#        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        DOCKER_VER=${VERSION#"v"}
        docker build \
          -t $GCR/"$GKE_PROJECT"/"$IMAGE":latest \
          -t $GCR/"$GKE_PROJECT"/"$IMAGE":$DOCKER_VER \
          -t flowlab/"$IMAGE":latest \
          -t flowlab/"$IMAGE":"$DOCKER_VER" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg VERSION=$VERSION .

    # Push the Docker image to Google Container Registry
#    - name: Publish GCR
#      run: |
#        docker push $GCR/"$GKE_PROJECT"/"$IMAGE"

    - name: Setup DockerHub
      run: |
        docker login --username flowlab --password ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish DockerHub
      run: |
        docker push flowlab/$IMAGE